# Generated by Django 3.1.5 on 2021-01-09 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date',
            new_name='publication_date',
        ),
    ]
